### ISSUE TITLE
Caching behaviour frosh_tools.elasticsearch.enabled

### ISSUE THREAD

**Issue by SwissCommerce** [FriendsOfShopware/FroshTools#148] opened 2022-10-25 06:26 UTC
### PHP Version

8.0.23

### Shopware Version

6.4.14.0

### Actual behaviour

1. Try -> Update plugin, clear cache via admin

Whole Shop breaks with

`Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\RuntimeException: "You have requested a non-existent parameter "frosh_tools.elasticsearch.enabled"." at /home/www-data/shops/XXXXXXX/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php line 54 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException(code: 0): You have requested a non-existent parameter \"frosh_tools.elasticsearch.enabled\". at /home/www-data/shops/XXXXXX/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54)"} []`

2. Try -> Update plugin, clear cache via cli (cache:clear)

Now the shop runs as usual but when activating a plugin throws the same error

![image](https://user-images.githubusercontent.com/108347966/197698395-31a27342-13be-453a-b216-ad7bfa46d75e.png)

### Expected behaviour

Update plugin, clear cache, working shop

### Steps to Reproduce?

Not sure yet

**Comment by SwissCommerce** [comment] 2022-10-25 06:45
Seems like opcache_reset() solved this

**Comment by SwissCommerce** [comment] 2022-11-02 07:43
@shyim we still get this from time to time. Should this not be handled by a cache:clear instead of clearing the OP Cache ?

This only happens on clustered shops with +1 webservers. This worked flawlessly before the last update.

**Comment by Isengo1989** [comment] 2022-11-03 14:09
We sadly had to deactivate the plugin due to this issue on most of our cluster shops :disappointed:

**Comment by shyim** [comment] 2023-05-08 15:52
I will close this as I still cannot reproduce it

**Closed by shyim** 2023-05-08 15:52 UTC
Labels: kind/bug
